#!/bin/bash
set -ex

leader=$(is-leader)
if [[ $leader == True ]]; then
  connection_string=$(chlp unitdata get etcd.connection_string)
  patched_string=$(echo $connection_string | sed "s/2380/2379/")
  # maintain some backwords compatibility with the existing interface until it
  # is phased out w/ the layer rewrite.
  relation-set connection_string=$patched_string port=2379 public_address=`unit-get public-address`
fi
