#!/bin/bash
set -ex

leader=$(is-leader)
if [[ $leader == True ]]; then
  connection_string=$(chlp unitdata get etcd.connection_string)
  patched_string=$(echo $connection_string | sed "s/7001/4001/")
  # maintain some backwords compatibility with the existing interface until it
  # is phased out w/ the layer rewrite.
  relation-set connection_string=$patched_string port=4001 public_address=`unit-get public-address`
fi
